apiVersion: apps/v1
kind: Deployment
metadata:
  name: hirebean-backend
  namespace: hirebean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hirebean-backend
  template:
    metadata:
      labels:
        app: hirebean-backend
    spec:
      containers:
        - name: hirebean-backend
          image: uchihadari/hirebean-backend:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/hirebean_db
            - name: HIREBEAN_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hirebean-db-secret
                  key: HIREBEAN_DB_USERNAME
            - name: HIREBEAN_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: hirebean-db-secret
                  key: HIREBEAN_DB_PASS

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          ports:
            - containerPort: 8080

